### PR TITLE
features branch

### PR DESCRIPTION
**Pull request by lubwamabenja**
This branch contains all my UI templates which could be accessed on https://lubwamabenja.github.io/Store-Manager/

stories for different braches could be accessed on https://www.pivotaltracker.com/n/projects/2203791

@armstrongsouljah @RLubwama @fahadmak @mwinel @WalujoEmmanuel @codjoero @oma0256 @sanya-kenneth @ruju256 @kaggwachristopher @bekeplar @habatkasa @amcodex

### CODE REVIEW

**Comment by oma0256** [comment]
@lubwamabenja I suggest you look at you're login I have failed to login

**Comment by lubwamabenja** [comment]
It's down in red

**Comment by oma0256** [comment]
@lubwamabenja tried to login with those cridentials but failed

**Comment by bekeplar** [comment]
its a good stuff Benja

**Pull request closed without merging**
